### ISSUE TITLE
unwrap on diffusion phenomena? 

### ISSUE THREAD

**Issue by georopon** [jhenin/qwrap#4]
I really have a problem, which does not let me sleep. During the diffusion process (where I want to observe the input of an ion to a channel), I have been using the wrapAll and wrapWater on options in the config file, at the end of the simulation I have been able to see that there is really the input of ions, but Many authors say that you have to "unwrap" the trajectory, when doing diffusion analysis, then, I have done it, using pbc both only for the ions and for the whole system and in both cases it is not seen that the ion penetrates, so I thought about extending the dynamics, but what happens is that when I extend the dynamics, the structure with which I start is the one that is inside the channel, so all this causes me enormous confusion.
Please, could you tell me in which cases wrapAll or wrapWater can be used in a dynamic.

**Comment by jhenin** [comment]
For the simulation it does not matter. To analyze binding, look at wrapped coordinates. For diffusion, look at unwrapped coordinates.
