### ISSUE TITLE
Use of Qwrap on Supercomputing Cluster

### ISSUE THREAD

**Issue by christos-efthymiou** [jhenin/qwrap#6]
I would like to use qwrap, but I need to perform my calculations on a supercomputer. I do not have administrative access on the supercomputer. I see that it says in the documentation that qwrap can be used without installation by using the command load path_to/qwrap.so. However, I have downloaded the repository and do not see a qwrap.so file. How can I create or find this file to be able to use qwrap on a supercomputer? Would I create this file on my personal computer and then transfer it so the supercomputer? I use a Windows computer but the supercomputer is linux based.

**Comment by jhenin** [comment]
Hi @christos-efthymiou , the ".so" file needs to be compiled on the supercomputer. Change the TCLINC and TCLLIB paths in the Makefile to point to the Tcl library there (`tcl.h` and `libtcl8.x.so`, respectively). Then type `make`, and you should have qwrap.so.

**Comment by jhenin** [comment]
Hi @christos-efthymiou , I've changed the build system to make the binaries more portable. Try downloading the current master branch and using the so files in the Linux directory. Please let me know how it goes.

**Comment by christos-efthymiou** [comment]
Hi @jhenin, thanks so much for making the binaries more portable! I was able to use the program successfully on the supercomputer with the so files in the Linux directory.
